-- ============================================================
-- 墨笺博客 · Supabase 建表脚本
-- 在 Supabase 控制台 → SQL Editor 里粘贴并运行
-- ============================================================

-- 1) 分类表
create table if not exists categories (
  id bigint generated by default as identity primary key,
  name text not null,
  description text
);

-- 2) 文章表
create table if not exists posts (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null default '',
  excerpt text not null default '',
  category_id bigint references categories(id) on delete set null,
  tags text[] default '{}',
  cover text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 3) 开启行级安全（RLS）
alter table categories enable row level security;
alter table posts enable row level security;

-- 管理员白名单。该表只能通过 Supabase SQL Editor / service_role 写入，
-- 前端没有新增管理员的权限。
create table if not exists blog_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

-- 兼容已经创建过 posts 表的项目。
alter table posts add column if not exists excerpt text not null default '';
alter table blog_admins enable row level security;

-- 4) 访问策略
--   读：所有人可读（前台展示）
--   写：仅 blog_admins 白名单中的登录用户（后台管理）
drop policy if exists "public read categories" on categories;
drop policy if exists "auth write categories" on categories;
drop policy if exists "admin write categories" on categories;
drop policy if exists "public read posts" on posts;
drop policy if exists "auth write posts" on posts;
drop policy if exists "admin write posts" on posts;
drop policy if exists "admin read own membership" on blog_admins;

create policy "admin read own membership" on blog_admins for select
  using (user_id = auth.uid());

create policy "public read categories" on categories for select using (true);
create policy "admin write categories" on categories for all
  using (exists (select 1 from blog_admins where user_id = auth.uid()))
  with check (exists (select 1 from blog_admins where user_id = auth.uid()));

create policy "public read posts" on posts for select using (true);
create policy "admin write posts" on posts for all
  using (exists (select 1 from blog_admins where user_id = auth.uid()))
  with check (exists (select 1 from blog_admins where user_id = auth.uid()));

-- 创建 Auth 管理员账号后，在 SQL Editor 中执行一次：
-- insert into blog_admins (user_id)
-- select id from auth.users where email = '你的管理员邮箱';

-- ============================================================
-- 初始数据（从原 mock 数据迁移，可选）
-- ============================================================
-- 分类种子数据
insert into categories (id, name, description) values (1, '日常', '生活随笔');
insert into categories (id, name, description) values (2, '技术', '前端学习');
insert into categories (id, name, description) values (3, '读书', '读书笔记');

-- 文章种子数据
insert into posts (title, content, category_id, tags, cover, created_at, updated_at) values ('Hello World', '# Hello

这是我的第一篇文章', 1, array['建站','Vue']::text[], NULL, '2026-01-01T00:00:00Z', '2026-01-01T00:00:00Z');
insert into posts (title, content, category_id, tags, cover, created_at, updated_at) values ('Vue 3 学习笔记', '# Vue 3 Composition API', 2, array['Vue','学习']::text[], NULL, '2026-01-05T00:00:00Z', '2026-01-05T00:00:00Z');
insert into posts (title, content, category_id, tags, cover, created_at, updated_at) values ('Pinia 状态管理入门', '# Pinia', 2, array['Pinia','Vue','状态管理']::text[], NULL, '2026-01-10T00:00:00Z', '2026-01-10T00:00:00Z');
insert into posts (title, content, category_id, tags, cover, created_at, updated_at) values ('生活随笔：春天来了', '# 春天来了', 1, array['生活','随笔']::text[], NULL, '2026-02-01T00:00:00Z', '2026-02-01T00:00:00Z');
insert into posts (title, content, category_id, tags, cover, created_at, updated_at) values ('TypeScript 类型体操练习', '# TypeScript 类型练习', 2, array['TypeScript','学习']::text[], NULL, '2026-02-15T00:00:00Z', '2026-02-15T00:00:00Z');
insert into posts (title, content, category_id, tags, cover, created_at, updated_at) values ('读书笔记：深入理解计算机系统', '# CSAPP 读书笔记

## 第一章：计算机系统漫游

- 信息就是位+上下文
- 程序的生命周期：预处理 → 编译 → 汇编 → 链接

## 重要概念

1. **缓存的重要性**：利用局部性原理提升性能
2. **存储器层次结构**：寄存器 > L1 > L2 > L3 > 内存 > 磁盘', 3, array['读书','计算机基础']::text[], NULL, 'now()', '2026-05-27T07:42:55.245Z');
