import psycopg2

conn = psycopg2.connect(
    host='db.mpyonapwrciipgbjkkcv.supabase.co',
    port=5432,
    dbname='postgres',
    user='postgres',
    password='Yzc3023209092@'
)
conn.autocommit = True
cur = conn.cursor()

# 建分类表
cur.execute("""
create table if not exists categories (
  id bigint generated by default as identity primary key,
  name text not null,
  description text
);
""")
print('categories table created')

# 建文章表
cur.execute("""
create table if not exists posts (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null default '',
  category_id bigint references categories(id) on delete set null,
  tags text[] default '{}',
  cover text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
""")
print('posts table created')

# 开启 RLS
cur.execute('alter table categories enable row level security;')
cur.execute('alter table posts enable row level security;')
print('RLS enabled')

# 删除旧策略
cur.execute('DROP POLICY IF EXISTS "public read categories" ON categories;')
cur.execute('DROP POLICY IF EXISTS "auth write categories" ON categories;')
cur.execute('DROP POLICY IF EXISTS "public read posts" ON posts;')
cur.execute('DROP POLICY IF EXISTS "auth write posts" ON posts;')
print('old policies dropped')

# 创建策略
cur.execute('create policy "public read categories" on categories for select using (true);')
cur.execute("""create policy "auth write categories" on categories for all
  using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');""")
cur.execute('create policy "public read posts" on posts for select using (true);')
cur.execute("""create policy "auth write posts" on posts for all
  using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');""")
print('policies created')

# 插入分类数据
cur.execute('DELETE FROM posts;')
cur.execute('DELETE FROM categories;')
cur.execute("INSERT INTO categories (id, name, description) VALUES (1, '日常', '生活随笔');")
cur.execute("INSERT INTO categories (id, name, description) VALUES (2, '技术', '前端学习');")
cur.execute("INSERT INTO categories (id, name, description) VALUES (3, '读书', '读书笔记');")
print('categories seeded')

# 插入文章数据
cur.execute("""INSERT INTO posts (title, content, category_id, tags, cover, created_at, updated_at) VALUES
('Hello World', '# Hello\n\n这是我的第一篇文章', 1, ARRAY['建站','Vue']::text[], NULL, '2026-01-01T00:00:00Z', '2026-01-01T00:00:00Z'),
('Vue 3 学习笔记', '# Vue 3 Composition API', 2, ARRAY['Vue','学习']::text[], NULL, '2026-01-05T00:00:00Z', '2026-01-05T00:00:00Z'),
('Pinia 状态管理入门', '# Pinia', 2, ARRAY['Pinia','Vue','状态管理']::text[], NULL, '2026-01-10T00:00:00Z', '2026-01-10T00:00:00Z'),
('生活随笔：春天来了', '# 春天来了', 1, ARRAY['生活','随笔']::text[], NULL, '2026-02-01T00:00:00Z', '2026-02-01T00:00:00Z'),
('TypeScript 类型体操练习', '# TypeScript 类型练习', 2, ARRAY['TypeScript','学习']::text[], NULL, '2026-02-15T00:00:00Z', '2026-02-15T00:00:00Z'),
('读书笔记：深入理解计算机系统', '# CSAPP 读书笔记

## 第一章：计算机系统漫游

- 信息就是位+上下文
- 程序的生命周期：预处理 → 编译 → 汇编 → 链接

## 重要概念

1. **缓存的重要性**：利用局部性原理提升性能
2. **存储器层次结构**：寄存器 > L1 > L2 > L3 > 内存 > 磁盘', 3, ARRAY['读书','计算机基础']::text[], NULL, now(), '2026-05-27T07:42:55.245Z');
""")
print('posts seeded')

# 验证
cur.execute('SELECT count(*) FROM categories;')
print(f'categories count: {cur.fetchone()[0]}')
cur.execute('SELECT count(*) FROM posts;')
print(f'posts count: {cur.fetchone()[0]}')

cur.close()
conn.close()
print('Done!')
